-- sql/schema.sql

-- ============================================
-- STOCKANALYTICS - DATABASE SCHEMA
-- ============================================

-- Tabela 1: Pre?os hist?ricos das a??es
CREATE TABLE IF NOT EXISTS stock_prices (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    date DATE NOT NULL,
    open DECIMAL(10,4),
    high DECIMAL(10,4),
    low DECIMAL(10,4),
    close DECIMAL(10,4),
    volume BIGINT,
    dividends DECIMAL(10,6) DEFAULT 0,
    stock_splits DECIMAL(10,4) DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(ticker, date)
);

-- Tabela 2: Indicadores t?cnicos calculados
CREATE TABLE IF NOT EXISTS technical_indicators (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    date DATE NOT NULL,
    sma_20 DECIMAL(10,4),
    sma_50 DECIMAL(10,4),
    sma_200 DECIMAL(10,4),
    rsi_14 DECIMAL(6,2),
    macd DECIMAL(10,6),
    macd_signal DECIMAL(10,6),
    bb_upper DECIMAL(10,4),
    bb_middle DECIMAL(10,4),
    bb_lower DECIMAL(10,4),
    daily_return DECIMAL(8,6),
    volatility_30d DECIMAL(8,6),
    UNIQUE(ticker, date)
);

-- Tabela 3: M?tricas fundamentalistas
CREATE TABLE IF NOT EXISTS stock_fundamentals (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) UNIQUE NOT NULL,
    company_name VARCHAR(200),
    sector VARCHAR(100),
    industry VARCHAR(200),
    market_cap BIGINT,
    pe_ratio DECIMAL(10,2),
    forward_pe DECIMAL(10,2),
    peg_ratio DECIMAL(10,4),
    price_to_book DECIMAL(10,4),
    dividend_yield DECIMAL(8,6),
    profit_margin DECIMAL(8,6),
    revenue_growth DECIMAL(8,6),
    earnings_growth DECIMAL(8,6),
    debt_to_equity DECIMAL(10,4),
    current_ratio DECIMAL(8,4),
    beta DECIMAL(6,4),
    week_52_high DECIMAL(10,4),
    week_52_low DECIMAL(10,4),
    last_updated TIMESTAMP DEFAULT NOW()
);

-- Tabela 4: M?tricas de risco calculadas
CREATE TABLE IF NOT EXISTS risk_metrics (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) UNIQUE NOT NULL,
    sharpe_ratio DECIMAL(8,4),
    sortino_ratio DECIMAL(8,4),
    max_drawdown DECIMAL(8,6),
    var_95 DECIMAL(8,6),
    annualized_return DECIMAL(8,6),
    annualized_volatility DECIMAL(8,6),
    calculated_at TIMESTAMP DEFAULT NOW()
);

-- Tabela 5: Sinais de trading
CREATE TABLE IF NOT EXISTS trading_signals (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    signal_date DATE NOT NULL,
    signal_type VARCHAR(50) NOT NULL,
    signal_strength VARCHAR(20),
    description TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(ticker, signal_date, signal_type)
);

-- ?ndices para performance
CREATE INDEX idx_prices_ticker_date ON stock_prices(ticker, date);
CREATE INDEX idx_indicators_ticker_date ON technical_indicators(ticker, date);
CREATE INDEX idx_signals_date ON trading_signals(signal_date);
CREATE INDEX idx_fundamentals_sector ON stock_fundamentals(sector);

-- Coment?rios (documenta??o do schema)
COMMENT ON TABLE stock_prices IS 'Historical OHLCV data for tracked stocks';
COMMENT ON TABLE technical_indicators IS 'Calculated technical indicators per stock/day';
COMMENT ON TABLE stock_fundamentals IS 'Fundamental analysis metrics (updated weekly)';
COMMENT ON TABLE risk_metrics IS 'Risk/return metrics calculated from price history';
COMMENT ON TABLE trading_signals IS 'Buy/sell signals generated by analysis';
